### ISSUE TITLE
Change how cache works in sonar workflow

### ISSUE THREAD

**Issue by pythoninja** [randomicu/ipconf#7]
```
steps:
- uses: actions/checkout@v2
- uses: actions/setup-java@v2
  with:
    distribution: 'temurin'
    java-version: '11'
    cache: 'maven'
- name: Build with Maven
  run: mvn -B package --file pom.xml
```

Ref: https://github.com/actions/setup-java#caching-packages-dependencies
